# Generated by Django 3.1.2 on 2020-12-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('ssn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
        ),
    ]
