# Generated by Django 3.0.3 on 2020-12-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automateregister',
            old_name='discord_webhooklink',
            new_name='discordwebhooklink',
        ),
        migrations.RenameField(
            model_name='automateregister',
            old_name='msteam_gmail_id',
            new_name='msteamgmailid',
        ),
        migrations.RenameField(
            model_name='automateregister',
            old_name='msteam_organisation_name',
            new_name='msteamorganisationname',
        ),
        migrations.RenameField(
            model_name='automateregister',
            old_name='msteam_password',
            new_name='msteampassword',
        ),
    ]
