# Generated by Django 3.1.2 on 2020-12-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
                ('sem', models.IntegerField(default=1)),
                ('course', models.ManyToManyField(to='register.Course')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='classrm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.classroom'),
        ),
    ]
